services:
  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - observability-net

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - observability-net

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.111.0
    command: [ "--config=/etc/otelcol/config.yaml" ]
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol/config.yaml
    ports:
      - "4317:4317"
      - "4318:4318"
      - "8889:8889"  # Prometheus exporter endpoint for Prometheus to scrape

    depends_on:
      - loki
      - prometheus
    networks:
      - observability-net
  
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      # Mount the prometheus config file into the container
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090" # Prometheus UI
    networks:
      - observability-net

networks:
  observability-net:
    driver: bridge